on: [push, pull_request]
name: soldat
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout soldat repository
        uses: actions/checkout@v2
        with:
          path: soldat

      - name: Checkout launcher repository
        uses: actions/checkout@v2
        with:
          repository: rzaba0/soldat-launcher
          path: launcher

      - name: Install soldat dependencies
        run: |
          sudo apt-get install cmake git fpc libprotobuf-dev protobuf-compiler libssl-dev libsdl2-dev libopenal-dev libphysfs-dev libfreetype6

      - name: Compile soldat
        run: |
          cd soldat
          mkdir game-build
          cd game-build
          cmake .. -DCMAKE_INSTALL_PREFIX=../../launcher/soldat -DCMAKE_BUILD_TYPE=Release
          make
          make install

      - name: Compile server only
        run: |
          cd soldat
          mkdir server-build
          cd server-build
          cmake .. -DBUILD_CLIENT=0 -DCMAKE_INSTALL_PREFIX=./soldatserver -DCMAKE_BUILD_TYPE=Release
          make
          make install

      - name: Build launcher
        run: |
          cd launcher
          npm ci
          npm run make

      - name: Tar server-only build
        run: |
          tar -cvf soldatserver.tar -C soldat/server-build soldatserver

      - name: Upload game build
        uses: actions/upload-artifact@v2
        with:
          name: soldat-linux-x64
          path: launcher/out/make/zip/linux/x64/

      - name: Upload server-only build
        uses: actions/upload-artifact@v2
        with:
          name: soldatserver-linux-x64
          path: soldatserver.tar

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout soldat repository
        uses: actions/checkout@v2
        with:
          path: soldat

      - name: Checkout launcher repository
        uses: actions/checkout@v2
        with:
          repository: rzaba0/soldat-launcher
          path: launcher

      - name: Cache fpc
        id: fpc
        uses: actions/cache@v2
        with:
          path: C:\fpc
          key: freepascal

      - name: Cache vcpkg
        id: vcpkg-cache
        uses: actions/cache@v2
        with:
          path: C:\vcpkg\installed
          key: vcpkg-cache

      - name: Download freepascal
        if: steps.fpc.outputs.cache-hit != 'true'
        run: |
          curl -o C:\fpc32.exe ftp://mirror.freemirror.org/pub/fpc/dist/3.0.4/i386-win32/fpc-3.0.4.i386-win32.exe
          curl -o C:\fpc64.exe ftp://mirror.freemirror.org/pub/fpc/dist/3.0.4/i386-win32/fpc-3.0.4.i386-win32.cross.x86_64-win64.exe

      - name: Install freepascal
        if: steps.fpc.outputs.cache-hit != 'true'
        run: |
           C:\fpc32.exe /silent /nocancel /suppressmsgboxes=no
           C:\fpc64.exe /silent /nocancel /suppressmsgboxes=no
        shell: cmd

      - name: Install dependencies
        run: |
          vcpkg.exe --triplet x64-windows install sdl2 physfs openssl protobuf freetype openal-soft

      - name: Build soldat
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          set PATH=%PATH%;C:\fpc\3.0.4\bin\i386-win32
          set OPENSSL_ROOT_DIR=C:\vcpkg\installed\x64-windows
          set PHYSFSDIR=C:\vcpkg\installed\x64-windows
          cd soldat
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCROSS_WINDOWS_64=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../launcher/soldat -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake"  -DSDL2_BUILDING_LIBRARY=1 ..
          nmake
          nmake install
        shell: cmd

      - name: Build launcher
        run: |
          cd launcher
          npm ci
          npm run make

      - uses: actions/upload-artifact@v2
        with:
          name: soldat-windows-x64
          path: launcher/out/make/zip/win32/x64/
